config/routes.rb
Classifieds::Application.routes.draw do
  resources :adverts

  resources :categories

  resources :users

  get "adverts/index"
 get 'my_account' => 'member#account'
  root :to => 'adverts#index'
  controller :session do
    get 'login' => :new
	post 'login' => :create
	get 'logout' => :destroy
end 

  get "/:id" => 'pages#show'
  
end

app/models/advert.rb
class Advert < ActiveRecord::Base
  attr_accessible :category_id, :contact_details, :description, :title, :user_id, :approved, :image
  belongs_to :category
  belongs_to :user
  
  has_attached_file :image
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  # GET /adverts
  # GET /adverts.json
  def index
    @adverts = Advert.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @adverts }
    end
  end

  # GET /adverts/1
  # GET /adverts/1.json
  def show
    @advert = Advert.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @advert }
    end
  end

  # GET /adverts/new
  # GET /adverts/new.json
  def new
    @advert = Advert.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @advert }
    end
  end

  # GET /adverts/1/edit
  def edit
    @advert = Advert.find(params[:id])
  end

  # POST /adverts
  # POST /adverts.json
  def create
    @advert = Advert.new(params[:advert])

    respond_to do |format|
      if @advert.save
        format.html { redirect_to @advert, notice: 'Advert was successfully created.' }
        format.json { render json: @advert, status: :created, location: @advert }
      else
        format.html { render action: "new" }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /adverts/1
  # PUT /adverts/1.json
  def update
    @advert = Advert.find(params[:id])

    respond_to do |format|
      if @advert.update_attributes(params[:advert])
        format.html { redirect_to @advert, notice: 'Advert was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adverts/1
  # DELETE /adverts/1.json
  def destroy
    @advert = Advert.find(params[:id])
    @advert.destroy

    respond_to do |format|
      format.html { redirect_to adverts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/views/adverts/_form.html.erb
<%= simple_form_for @advert, :html => { :multipart => true } do |f| %>
  
  <%= f.error_notification %>
    <div class="form-inputs">
      <% if admin? %>
          <%= f.association :user %>
          <%= f.input :approved %>
      <% end %>
      <%= f.input :title %>
	  <%= f.input :image %>
      <%= f.input :description %>
      <%= f.input :contact_details %>
      <%= f.association :category, as: :radio_buttons %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/adverts/edit.html.erb
<h1>Editing advert</h1>

<%= render 'form' %>

<%= link_to 'Show', @advert %> |
<%= link_to 'Back', adverts_path %>

app/views/adverts/index.html.erb
<h1>Listing adverts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Contact details</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @adverts.each do |advert| %>
  <tr>
    <td><%= advert.title %></td>
    <td><%= advert.description %></td>
    <td><%= advert.contact_details %></td>
    <td><%= advert.category_id %></td>
    <td><%= link_to 'Show', advert %></td>
    <td><%= link_to 'Edit', edit_advert_path(advert) %></td>
    <td><%= link_to 'Destroy', advert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Advert', new_advert_path %>

app/views/adverts/index2.html.erb
<h1>All the Listings</h1>
<br/>
<br/>
<h2>Real Estate</h2>
<br/>
<div class="container">
  <h3>I want to sell my house</h3>
  <br/>
  <%= image_tag "01.jpg", class: "alignleft border" %>
  I want to sell my house <br/>
  I want to sell my house <br/>
  I want to sell my house <br/>
  I want to sell my house <br/>
  <br/>
  <a class="link">View details</a>
</div>

app/views/adverts/new.html.erb
<h1>New advert</h1>

<%= render 'form' %>

<%= link_to 'Back', adverts_path %>

app/views/adverts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @advert.title %>
</p>
<p>
<%= image_tag @advert.image.url(:medium) %>
</p>
<p>
  <b>Description:</b>
  <%= @advert.description %>
</p>

<p>
  <b>Contact details:</b>
  <%= @advert.contact_details %>
</p>

<p>
  <b>Category:</b>
  <%= @advert.category_id %>
</p>

<%= link_to 'Edit', edit_advert_path(@advert) %> |
<%= link_to 'Back', adverts_path %>